### ISSUE TITLE
Makefile for Linux

### ISSUE THREAD

**Issue by Compyx** [cadaver/miniplayer#1]
Hi there,

To get gt2mini to compile on Linix, the `Makefile` needs to be altered a bit:
```make
all: gt2mini example.prg example.sid

clean:
	rm -f gt2mini
	rm -f *.prg
	rm -f *.sid

gt2mini: gt2mini.c fileio.c
	gcc gt2mini.c fileio.c -o gt2mini

example.prg: gt2mini mw4title.sng prgexample.s player.s
	./gt2mini mw4title.sng musicmodule.s -s1000
	dasm musicmodule.s -omusicmodule.bin -p3 -f3
	dasm prgexample.s -oexample.prg -p3

example.sid: gt2mini mw4title.sng sidexample.s player.s
	./gt2mini mw4title.sng musicdata.s -b
	dasm sidexample.s -oexample.sid -p3 -f3
```

Perhaps you could add this as `Makefile-Linux` or something?

Also, with the dasm I used (http://csdb.dk/release/?id=103250), I had to put quotes around the include arguments.

Cheers,
Compyx

**Comment by cadaver** [comment]
Thanks. Should be no problem to include. Please check the changes and close the issue if resolved, I had to add the quotes "blind", because on Windows they were apparently not needed, even with that DASM version.

**Comment by Compyx** [comment]
Works fine now, thanks!

Closing.
